import type { Metadata } from "next";
import "./globals.css";
import Alert from "@/components/toastify/Toastify";
import LenisProvider from "@/components/Lenis";
import Cursor from "@/components/Cursor";

export const metadata: Metadata = {
  title: "BBPH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="es">
      <body>
  
        <Cursor>
          <LenisProvider />
          {children}
          <Alert />
        </Cursor>
      </body>
    </html>
    </>
  );
}
